groups:
- name: Cosmos Alerts  
  rules:

  - alert: ValidatorMissingBlocks
    expr: rate(tendermint_consensus_validator_missed_blocks[5m]) > 10
    for: 1m
    labels:
      severity: major
    annotations:
      description: "Validator missing blocks (>=10 in last 5 minutes)"

  - alert: ValidatorDegradedSyncing
    expr: increase(tendermint_consensus_latest_block_height{skip_sync_alert!="true"}[10m]) < 20
    for: 10m
    labels:
      severity: major
    annotations:
      description: "Degraded syncing performance (less than 20 blocks in the last 10 min)"

  - alert: ValidatorTooFewPeers
    expr: tendermint_p2p_peers < 3
    for: 5m
    labels:
      severity: major
    annotations:
      description: "Number of peers is lower than threshold (<3)"

  - alert: MissingBlocks
    expr: increase(cosmos_validator_missed_blocks[5m]) > 10
    for: 5m
    labels:
      severity: major
    annotations:
      description: 'Validator `{{ $labels.moniker }}` is missing `{{ $value }}` blocks!'

  - alert: LowInRank
    expr: cosmos_validator_rank > (count(cosmos_validators_active == 1) - 10)
    for: 5m
    labels:
      severity: major
    annotations:
      description: 'Your validator `{{ $labels.moniker }}` rank is `{{ $value }}`!'

  - alert: UpInRank
    expr: cosmos_validator_rank > (count(cosmos_validators_active == 1) + 10)
    for: 5m
    labels:
      severity: major
    annotations:
      description: 'Your validator `{{ $labels.moniker }}` rank is `{{ $value }}`!'

  - alert: IsJailed
    expr: cosmos_validator_jailed == 1
    for: 5m
    labels:
      severity: major
    annotations:
      description: 'Your validator `{{ $labels.moniker }}` is jailed! `{{ $value }}`!'

  - alert: NodeFilesystemReadonly
    expr: node_filesystem_readonly{fstype!~"rootfs|nfs4"} > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Filesystem "{{ $labels.mountpoint }}" on "{{ $labels.instance }}" is read-only.'

  - alert: NodeDiskFull48H
    expr: predict_linear(node_filesystem_free_bytes{fstype!~"rootfs|nfs4|tmpfs"}[4h], 48 * 3600) < 0
    for: 5m
    labels:
      severity: major
    annotations:
      description: 'Filesystem "{{ $labels.mountpoint }}" on "{{ $labels.instance }}" will be out of diskspace within 48 hours.'
    
  - alert: NodeOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
    for: 2m
    labels:
      severity: major
    annotations:
      description: 'Node memory is filling up < 10% left\n  VALUE = {{ $value }}\n LABELS: {{ $labels.instance }}'

  - alert: NodeHighCPULoad
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
    for: 0m
    labels:
      severity: major
    annotations:
      description: 'CPU load is > 80%\n  VALUE = {{ $value }}\n LABELS: {{ $labels.instance }}'

  - alert: NodeTimeOutOfSync
    expr: node_timex_sync_status{} != 1
    for: 5m
    labels:
      severity: major
    annotations:
      description: 'Time on instance "{{ $labels.instance }}" not in sync with NTP.'