{
 "title": "Cosmos Validator",
 "description": "Dashboard to monitor cosmos validator",
 "tags": [
  "cosmos",
  "blockchain",
  "validator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "chain_id",
    "query": {
     "query": "label_values(cosmos_validators_status, chain_id)"
    }
   },
   {
    "name": "moniker",
    "label": "moniker",
    "query": {
     "query": "label_values(cosmos_validator_status, moniker)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_memory_MemTotal_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Validator health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "\r\n<table style=\"width:100%; height:100%;border:0px solid black;\">\r\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><center><img width=\"300px\" src=\"https://avatars.githubusercontent.com/u/122169371?v=4\" /></td>\r\n</table>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "description": "Height of the chain",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\"}"
    }
   ]
  },
  { "title": "Total Transactions", "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 } },
  {
   "title": "Syncing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_state_syncing{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_active{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  { "title": "Block Size", "gridPos": { "h": 4, "w": 6, "x": 4, "y": 5 } },
  {
   "title": "Missed blocks",
   "type": "stat",
   "description": "Number of missed blocks",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tendermint_consensus_validator_missed_blocks{chain_id=\"$chain_id\", instance=\"$instance\"}[1h])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Jailed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_jailed{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "Missed blocks",
   "type": "timeseries",
   "description": "Validator missed blocks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_missed_blocks{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "description": "Number of block produced last minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(tendermint_consensus_height{chain_id=\"$chain_id\"}[1m])"
    }
   ]
  },
  {
   "title": "Validator Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "chain_id",
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime CT",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=\"$instance\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(cosmos_validator_rank{chain_id=\"$chain_id\", moniker=\"$moniker\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Total delegations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (denom)",
     "legendFormat": "{{ denom }}"
    }
   ]
  },
  {
   "title": "Commission rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_commission_rate{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "Delegations count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Top validators missing blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, cosmos_validators_missed_blocks{chain_id=\"$chain_id\"} > 0))"
    }
   ]
  },
  {
   "title": "Online validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators-tendermint_consensus_missing_validators{chain_id=\"$chain_id\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Confirmed Tx",
   "type": "stat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Offline: voting power %",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\"} / tendermint_consensus_validators_power{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Validators missing blocks",
   "type": "stat",
   "description": "Number of validators missing blocks",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_missed_blocks{chain_id=\"$chain_id\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Voting power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validator_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Voting power"
    }
   ]
  },
  {
   "title": "Last block sign delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance\"} - on() tendermint_consensus_validator_last_signed_height{chain_id=\"$chain_id\", instance=\"$instance\"} - 1",
     "legendFormat": "Sign delay"
    }
   ]
  },
  {
   "title": "Missed signs hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tendermint_consensus_validator_missed_blocks{chain_id=\"$chain_id\", instance=\"$instance\"}[1h])",
     "legendFormat": "Missed"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Transactions"
    }
   ]
  }
 ]
}